//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefBrowserView : CefView
    {
        internal static CefBrowserView FromNative(cef_browser_view_t* ptr)
        {
            return new CefBrowserView(ptr);
        }
        
        internal static CefBrowserView FromNativeOrNull(cef_browser_view_t* ptr)
        {
            if (ptr == null) return null;
            return new CefBrowserView(ptr);
        }
        
        private CefBrowserView(cef_browser_view_t* ptr)
            : base((cef_view_t*)ptr) {}
        
        internal new cef_browser_view_t* ToNative()
        {
            AddRef();
            return (cef_browser_view_t*)_self;
        }
    }
}
