//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefBoxLayout : CefLayout
    {
        internal static CefBoxLayout FromNative(cef_box_layout_t* ptr)
        {
            return new CefBoxLayout(ptr);
        }
        
        internal static CefBoxLayout FromNativeOrNull(cef_box_layout_t* ptr)
        {
            if (ptr == null) return null;
            return new CefBoxLayout(ptr);
        }
        
        private CefBoxLayout(cef_box_layout_t* ptr)
            : base((cef_layout_t*)ptr) {}
        
        internal new cef_box_layout_t* ToNative()
        {
            AddRef();
            return (cef_box_layout_t*)_self;
        }
    }
}
