//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: HANDLER
    public abstract unsafe partial class CefBrowserViewDelegate
    {
        private static Dictionary<IntPtr, CefBrowserViewDelegate> _roots = new Dictionary<IntPtr, CefBrowserViewDelegate>();
        
        private int _refct;
        private cef_browser_view_delegate_t* _self;
        
        protected object SyncRoot { get { return this; } }
        
        private cef_browser_view_delegate_t.add_ref_delegate _ds0;
        private cef_browser_view_delegate_t.release_delegate _ds1;
        private cef_browser_view_delegate_t.has_one_ref_delegate _ds2;
        private cef_browser_view_delegate_t.has_at_least_one_ref_delegate _ds3;
        private cef_view_delegate_t.get_preferred_size_delegate _ds4;
        private cef_view_delegate_t.get_minimum_size_delegate _ds5;
        private cef_view_delegate_t.get_maximum_size_delegate _ds6;
        private cef_view_delegate_t.get_height_for_width_delegate _ds7;
        private cef_view_delegate_t.on_parent_view_changed_delegate _ds8;
        private cef_view_delegate_t.on_child_view_changed_delegate _ds9;
        private cef_view_delegate_t.on_window_changed_delegate _dsa;
        private cef_view_delegate_t.on_layout_changed_delegate _dsb;
        private cef_view_delegate_t.on_focus_delegate _dsc;
        private cef_view_delegate_t.on_blur_delegate _dsd;
        private cef_view_delegate_t.on_theme_changed_delegate _dse;
        private cef_browser_view_delegate_t.on_browser_created_delegate _dsf;
        private cef_browser_view_delegate_t.on_browser_destroyed_delegate _ds10;
        private cef_browser_view_delegate_t.get_delegate_for_popup_browser_view_delegate _ds11;
        private cef_browser_view_delegate_t.on_popup_browser_view_created_delegate _ds12;
        private cef_browser_view_delegate_t.get_chrome_toolbar_type_delegate _ds13;
        private cef_browser_view_delegate_t.use_frameless_window_for_picture_in_picture_delegate _ds14;
        private cef_browser_view_delegate_t.allow_move_for_picture_in_picture_delegate _ds15;
        private cef_browser_view_delegate_t.allow_picture_in_picture_without_user_activation_delegate _ds16;
        private cef_browser_view_delegate_t.on_gesture_command_delegate _ds17;
        private cef_browser_view_delegate_t.get_browser_runtime_style_delegate _ds18;
        
        protected CefBrowserViewDelegate()
        {
            _self = cef_browser_view_delegate_t.Alloc();
        
            _ds0 = new cef_browser_view_delegate_t.add_ref_delegate(add_ref);
            _self->_base._add_ref = Marshal.GetFunctionPointerForDelegate(_ds0);
            _ds1 = new cef_browser_view_delegate_t.release_delegate(release);
            _self->_base._release = Marshal.GetFunctionPointerForDelegate(_ds1);
            _ds2 = new cef_browser_view_delegate_t.has_one_ref_delegate(has_one_ref);
            _self->_base._has_one_ref = Marshal.GetFunctionPointerForDelegate(_ds2);
            _ds3 = new cef_browser_view_delegate_t.has_at_least_one_ref_delegate(has_at_least_one_ref);
            _self->_base._has_at_least_one_ref = Marshal.GetFunctionPointerForDelegate(_ds3);
            _ds4 = new cef_view_delegate_t.get_preferred_size_delegate(get_preferred_size);
            _self->_get_preferred_size = Marshal.GetFunctionPointerForDelegate(_ds4);
            _ds5 = new cef_view_delegate_t.get_minimum_size_delegate(get_minimum_size);
            _self->_get_minimum_size = Marshal.GetFunctionPointerForDelegate(_ds5);
            _ds6 = new cef_view_delegate_t.get_maximum_size_delegate(get_maximum_size);
            _self->_get_maximum_size = Marshal.GetFunctionPointerForDelegate(_ds6);
            _ds7 = new cef_view_delegate_t.get_height_for_width_delegate(get_height_for_width);
            _self->_get_height_for_width = Marshal.GetFunctionPointerForDelegate(_ds7);
            _ds8 = new cef_view_delegate_t.on_parent_view_changed_delegate(on_parent_view_changed);
            _self->_on_parent_view_changed = Marshal.GetFunctionPointerForDelegate(_ds8);
            _ds9 = new cef_view_delegate_t.on_child_view_changed_delegate(on_child_view_changed);
            _self->_on_child_view_changed = Marshal.GetFunctionPointerForDelegate(_ds9);
            _dsa = new cef_view_delegate_t.on_window_changed_delegate(on_window_changed);
            _self->_on_window_changed = Marshal.GetFunctionPointerForDelegate(_dsa);
            _dsb = new cef_view_delegate_t.on_layout_changed_delegate(on_layout_changed);
            _self->_on_layout_changed = Marshal.GetFunctionPointerForDelegate(_dsb);
            _dsc = new cef_view_delegate_t.on_focus_delegate(on_focus);
            _self->_on_focus = Marshal.GetFunctionPointerForDelegate(_dsc);
            _dsd = new cef_view_delegate_t.on_blur_delegate(on_blur);
            _self->_on_blur = Marshal.GetFunctionPointerForDelegate(_dsd);
            _dse = new cef_view_delegate_t.on_theme_changed_delegate(on_theme_changed);
            _self->_on_theme_changed = Marshal.GetFunctionPointerForDelegate(_dse);
            _dsf = new cef_browser_view_delegate_t.on_browser_created_delegate(on_browser_created);
            _self->_on_browser_created = Marshal.GetFunctionPointerForDelegate(_dsf);
            _ds10 = new cef_browser_view_delegate_t.on_browser_destroyed_delegate(on_browser_destroyed);
            _self->_on_browser_destroyed = Marshal.GetFunctionPointerForDelegate(_ds10);
            _ds11 = new cef_browser_view_delegate_t.get_delegate_for_popup_browser_view_delegate(get_delegate_for_popup_browser_view);
            _self->_get_delegate_for_popup_browser_view = Marshal.GetFunctionPointerForDelegate(_ds11);
            _ds12 = new cef_browser_view_delegate_t.on_popup_browser_view_created_delegate(on_popup_browser_view_created);
            _self->_on_popup_browser_view_created = Marshal.GetFunctionPointerForDelegate(_ds12);
            _ds13 = new cef_browser_view_delegate_t.get_chrome_toolbar_type_delegate(get_chrome_toolbar_type);
            _self->_get_chrome_toolbar_type = Marshal.GetFunctionPointerForDelegate(_ds13);
            _ds14 = new cef_browser_view_delegate_t.use_frameless_window_for_picture_in_picture_delegate(use_frameless_window_for_picture_in_picture);
            _self->_use_frameless_window_for_picture_in_picture = Marshal.GetFunctionPointerForDelegate(_ds14);
            _ds15 = new cef_browser_view_delegate_t.allow_move_for_picture_in_picture_delegate(allow_move_for_picture_in_picture);
            _self->_allow_move_for_picture_in_picture = Marshal.GetFunctionPointerForDelegate(_ds15);
            _ds16 = new cef_browser_view_delegate_t.allow_picture_in_picture_without_user_activation_delegate(allow_picture_in_picture_without_user_activation);
            _self->_allow_picture_in_picture_without_user_activation = Marshal.GetFunctionPointerForDelegate(_ds16);
            _ds17 = new cef_browser_view_delegate_t.on_gesture_command_delegate(on_gesture_command);
            _self->_on_gesture_command = Marshal.GetFunctionPointerForDelegate(_ds17);
            _ds18 = new cef_browser_view_delegate_t.get_browser_runtime_style_delegate(get_browser_runtime_style);
            _self->_get_browser_runtime_style = Marshal.GetFunctionPointerForDelegate(_ds18);
        }
        
        ~CefBrowserViewDelegate()
        {
            Dispose(false);
        }
        
        protected virtual void Dispose(bool disposing)
        {
            if (_self != null)
            {
                cef_browser_view_delegate_t.Free(_self);
                _self = null;
            }
        }
        
        private void add_ref(cef_browser_view_delegate_t* self)
        {
            lock (SyncRoot)
            {
                var result = ++_refct;
                if (result == 1)
                {
                    lock (_roots) { _roots.Add((IntPtr)_self, this); }
                }
            }
        }
        
        private int release(cef_browser_view_delegate_t* self)
        {
            lock (SyncRoot)
            {
                var result = --_refct;
                if (result == 0)
                {
                    lock (_roots) { _roots.Remove((IntPtr)_self); }
                    return 1;
                }
                return 0;
            }
        }
        
        private int has_one_ref(cef_browser_view_delegate_t* self)
        {
            lock (SyncRoot) { return _refct == 1 ? 1 : 0; }
        }
        
        private int has_at_least_one_ref(cef_browser_view_delegate_t* self)
        {
            lock (SyncRoot) { return _refct != 0 ? 1 : 0; }
        }
        
        internal cef_browser_view_delegate_t* ToNative()
        {
            add_ref(_self);
            return _self;
        }
        
        [Conditional("DEBUG")]
        private void CheckSelf(cef_browser_view_delegate_t* self)
        {
            if (_self != self) throw ExceptionBuilder.InvalidSelfReference();
        }
        
    }
}
