//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public unsafe partial class CefButton : CefView
    {
        internal static CefButton FromNative(cef_button_t* ptr)
        {
            return new CefButton(ptr);
        }
        
        internal static CefButton FromNativeOrNull(cef_button_t* ptr)
        {
            if (ptr == null) return null;
            return new CefButton(ptr);
        }
        
        private protected CefButton(cef_button_t* ptr)
            : base((cef_view_t*)ptr) {}
        
        internal new cef_button_t* ToNative()
        {
            return (cef_button_t*)_self;
        }
    }
}
