//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefFillLayout : CefLayout
    {
        internal static CefFillLayout FromNative(cef_fill_layout_t* ptr)
        {
            return new CefFillLayout(ptr);
        }
        
        internal static CefFillLayout FromNativeOrNull(cef_fill_layout_t* ptr)
        {
            if (ptr == null) return null;
            return new CefFillLayout(ptr);
        }
        
        private CefFillLayout(cef_fill_layout_t* ptr)
            : base((cef_layout_t*)ptr) {}
        
        internal new cef_fill_layout_t* ToNative()
        {
            return (cef_fill_layout_t*)_self;
        }
    }
}
