//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public unsafe partial class CefLabelButton : CefButton
    {
        internal static CefLabelButton FromNative(cef_label_button_t* ptr)
        {
            return new CefLabelButton(ptr);
        }
        
        internal static CefLabelButton FromNativeOrNull(cef_label_button_t* ptr)
        {
            if (ptr == null) return null;
            return new CefLabelButton(ptr);
        }
        
        private protected CefLabelButton(cef_label_button_t* ptr)
            : base((cef_button_t*)ptr) {}
        
        internal new cef_label_button_t* ToNative()
        {
            AddRef();
            return (cef_label_button_t*)_self;
        }
    }
}
