//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefMenuButton : CefLabelButton
    {
        internal static CefMenuButton FromNative(cef_menu_button_t* ptr)
        {
            return new CefMenuButton(ptr);
        }
        
        internal static CefMenuButton FromNativeOrNull(cef_menu_button_t* ptr)
        {
            if (ptr == null) return null;
            return new CefMenuButton(ptr);
        }
        
        private CefMenuButton(cef_menu_button_t* ptr)
            : base((cef_label_button_t*)ptr) {}
        
        internal new cef_menu_button_t* ToNative()
        {
            AddRef();
            return (cef_menu_button_t*)_self;
        }
    }
}
