//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: HANDLER
    public abstract unsafe partial class CefPanelDelegate
    {
        private static Dictionary<IntPtr, CefPanelDelegate> _roots = new Dictionary<IntPtr, CefPanelDelegate>();
        
        private int _refct;
        private cef_panel_delegate_t* _self;
        
        protected object SyncRoot { get { return this; } }
        
        private cef_panel_delegate_t.add_ref_delegate _ds0;
        private cef_panel_delegate_t.release_delegate _ds1;
        private cef_panel_delegate_t.has_one_ref_delegate _ds2;
        private cef_panel_delegate_t.has_at_least_one_ref_delegate _ds3;
        private cef_view_delegate_t.get_preferred_size_delegate _ds4;
        private cef_view_delegate_t.get_minimum_size_delegate _ds5;
        private cef_view_delegate_t.get_maximum_size_delegate _ds6;
        private cef_view_delegate_t.get_height_for_width_delegate _ds7;
        private cef_view_delegate_t.on_parent_view_changed_delegate _ds8;
        private cef_view_delegate_t.on_child_view_changed_delegate _ds9;
        private cef_view_delegate_t.on_window_changed_delegate _dsa;
        private cef_view_delegate_t.on_layout_changed_delegate _dsb;
        private cef_view_delegate_t.on_focus_delegate _dsc;
        private cef_view_delegate_t.on_blur_delegate _dsd;
        private cef_view_delegate_t.on_theme_changed_delegate _dse;
        
        protected CefPanelDelegate()
        {
            _self = cef_panel_delegate_t.Alloc();
        
            _ds0 = new cef_panel_delegate_t.add_ref_delegate(add_ref);
            _self->_base._add_ref = Marshal.GetFunctionPointerForDelegate(_ds0);
            _ds1 = new cef_panel_delegate_t.release_delegate(release);
            _self->_base._release = Marshal.GetFunctionPointerForDelegate(_ds1);
            _ds2 = new cef_panel_delegate_t.has_one_ref_delegate(has_one_ref);
            _self->_base._has_one_ref = Marshal.GetFunctionPointerForDelegate(_ds2);
            _ds3 = new cef_panel_delegate_t.has_at_least_one_ref_delegate(has_at_least_one_ref);
            _self->_base._has_at_least_one_ref = Marshal.GetFunctionPointerForDelegate(_ds3);
            _ds4 = new cef_view_delegate_t.get_preferred_size_delegate(get_preferred_size);
            _self->_get_preferred_size = Marshal.GetFunctionPointerForDelegate(_ds4);
            _ds5 = new cef_view_delegate_t.get_minimum_size_delegate(get_minimum_size);
            _self->_get_minimum_size = Marshal.GetFunctionPointerForDelegate(_ds5);
            _ds6 = new cef_view_delegate_t.get_maximum_size_delegate(get_maximum_size);
            _self->_get_maximum_size = Marshal.GetFunctionPointerForDelegate(_ds6);
            _ds7 = new cef_view_delegate_t.get_height_for_width_delegate(get_height_for_width);
            _self->_get_height_for_width = Marshal.GetFunctionPointerForDelegate(_ds7);
            _ds8 = new cef_view_delegate_t.on_parent_view_changed_delegate(on_parent_view_changed);
            _self->_on_parent_view_changed = Marshal.GetFunctionPointerForDelegate(_ds8);
            _ds9 = new cef_view_delegate_t.on_child_view_changed_delegate(on_child_view_changed);
            _self->_on_child_view_changed = Marshal.GetFunctionPointerForDelegate(_ds9);
            _dsa = new cef_view_delegate_t.on_window_changed_delegate(on_window_changed);
            _self->_on_window_changed = Marshal.GetFunctionPointerForDelegate(_dsa);
            _dsb = new cef_view_delegate_t.on_layout_changed_delegate(on_layout_changed);
            _self->_on_layout_changed = Marshal.GetFunctionPointerForDelegate(_dsb);
            _dsc = new cef_view_delegate_t.on_focus_delegate(on_focus);
            _self->_on_focus = Marshal.GetFunctionPointerForDelegate(_dsc);
            _dsd = new cef_view_delegate_t.on_blur_delegate(on_blur);
            _self->_on_blur = Marshal.GetFunctionPointerForDelegate(_dsd);
            _dse = new cef_view_delegate_t.on_theme_changed_delegate(on_theme_changed);
            _self->_on_theme_changed = Marshal.GetFunctionPointerForDelegate(_dse);
        }
        
        ~CefPanelDelegate()
        {
            Dispose(false);
        }
        
        protected virtual void Dispose(bool disposing)
        {
            if (_self != null)
            {
                cef_panel_delegate_t.Free(_self);
                _self = null;
            }
        }
        
        private void add_ref(cef_panel_delegate_t* self)
        {
            lock (SyncRoot)
            {
                var result = ++_refct;
                if (result == 1)
                {
                    lock (_roots) { _roots.Add((IntPtr)_self, this); }
                }
            }
        }
        
        private int release(cef_panel_delegate_t* self)
        {
            lock (SyncRoot)
            {
                var result = --_refct;
                if (result == 0)
                {
                    lock (_roots) { _roots.Remove((IntPtr)_self); }
                    return 1;
                }
                return 0;
            }
        }
        
        private int has_one_ref(cef_panel_delegate_t* self)
        {
            lock (SyncRoot) { return _refct == 1 ? 1 : 0; }
        }
        
        private int has_at_least_one_ref(cef_panel_delegate_t* self)
        {
            lock (SyncRoot) { return _refct != 0 ? 1 : 0; }
        }
        
        internal cef_panel_delegate_t* ToNative()
        {
            add_ref(_self);
            return _self;
        }
        
        [Conditional("DEBUG")]
        private void CheckSelf(cef_panel_delegate_t* self)
        {
            if (_self != self) throw ExceptionBuilder.InvalidSelfReference();
        }
        
    }
}
