//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public unsafe partial class CefPanel : CefView
    {
        internal static CefPanel FromNative(cef_panel_t* ptr)
        {
            return new CefPanel(ptr);
        }
        
        internal static CefPanel FromNativeOrNull(cef_panel_t* ptr)
        {
            if (ptr == null) return null;
            return new CefPanel(ptr);
        }
        
        private protected CefPanel(cef_panel_t* ptr)
            : base((cef_view_t*)ptr) {}
        
        internal new cef_panel_t* ToNative()
        {
            return (cef_panel_t*)_self;
        }
    }
}
