//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefScrollView : CefView
    {
        internal static CefScrollView FromNative(cef_scroll_view_t* ptr)
        {
            return new CefScrollView(ptr);
        }
        
        internal static CefScrollView FromNativeOrNull(cef_scroll_view_t* ptr)
        {
            if (ptr == null) return null;
            return new CefScrollView(ptr);
        }
        
        private CefScrollView(cef_scroll_view_t* ptr)
            : base((cef_view_t*)ptr) {}
        
        internal new cef_scroll_view_t* ToNative()
        {
            return (cef_scroll_view_t*)_self;
        }
    }
}
