//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefTextfield : CefView
    {
        internal static CefTextfield FromNative(cef_textfield_t* ptr)
        {
            return new CefTextfield(ptr);
        }
        
        internal static CefTextfield FromNativeOrNull(cef_textfield_t* ptr)
        {
            if (ptr == null) return null;
            return new CefTextfield(ptr);
        }
        
        private CefTextfield(cef_textfield_t* ptr)
            : base((cef_view_t*)ptr) {}
        
        internal new cef_textfield_t* ToNative()
        {
            return (cef_textfield_t*)_self;
        }
    }
}
