//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: HANDLER
    public abstract unsafe partial class CefWindowDelegate
    {
        private static Dictionary<IntPtr, CefWindowDelegate> _roots = new Dictionary<IntPtr, CefWindowDelegate>();
        
        private int _refct;
        private cef_window_delegate_t* _self;
        
        protected object SyncRoot { get { return this; } }
        
        private cef_window_delegate_t.add_ref_delegate _ds0;
        private cef_window_delegate_t.release_delegate _ds1;
        private cef_window_delegate_t.has_one_ref_delegate _ds2;
        private cef_window_delegate_t.has_at_least_one_ref_delegate _ds3;
        private cef_view_delegate_t.get_preferred_size_delegate _ds4;
        private cef_view_delegate_t.get_minimum_size_delegate _ds5;
        private cef_view_delegate_t.get_maximum_size_delegate _ds6;
        private cef_view_delegate_t.get_height_for_width_delegate _ds7;
        private cef_view_delegate_t.on_parent_view_changed_delegate _ds8;
        private cef_view_delegate_t.on_child_view_changed_delegate _ds9;
        private cef_view_delegate_t.on_window_changed_delegate _dsa;
        private cef_view_delegate_t.on_layout_changed_delegate _dsb;
        private cef_view_delegate_t.on_focus_delegate _dsc;
        private cef_view_delegate_t.on_blur_delegate _dsd;
        private cef_view_delegate_t.on_theme_changed_delegate _dse;
        private cef_window_delegate_t.on_window_created_delegate _dsf;
        private cef_window_delegate_t.on_window_closing_delegate _ds10;
        private cef_window_delegate_t.on_window_destroyed_delegate _ds11;
        private cef_window_delegate_t.on_window_activation_changed_delegate _ds12;
        private cef_window_delegate_t.on_window_bounds_changed_delegate _ds13;
        private cef_window_delegate_t.on_window_fullscreen_transition_delegate _ds14;
        private cef_window_delegate_t.get_parent_window_delegate _ds15;
        private cef_window_delegate_t.is_window_modal_dialog_delegate _ds16;
        private cef_window_delegate_t.get_initial_bounds_delegate _ds17;
        private cef_window_delegate_t.get_initial_show_state_delegate _ds18;
        private cef_window_delegate_t.is_frameless_delegate _ds19;
        private cef_window_delegate_t.with_standard_window_buttons_delegate _ds1a;
        private cef_window_delegate_t.get_titlebar_height_delegate _ds1b;
        private cef_window_delegate_t.accepts_first_mouse_delegate _ds1c;
        private cef_window_delegate_t.can_resize_delegate _ds1d;
        private cef_window_delegate_t.can_maximize_delegate _ds1e;
        private cef_window_delegate_t.can_minimize_delegate _ds1f;
        private cef_window_delegate_t.can_close_delegate _ds20;
        private cef_window_delegate_t.on_accelerator_delegate _ds21;
        private cef_window_delegate_t.on_key_event_delegate _ds22;
        private cef_window_delegate_t.on_theme_colors_changed_delegate _ds23;
        private cef_window_delegate_t.get_window_runtime_style_delegate _ds24;
        private cef_window_delegate_t.get_linux_window_properties_delegate _ds25;
        
        protected CefWindowDelegate()
        {
            _self = cef_window_delegate_t.Alloc();
        
            _ds0 = new cef_window_delegate_t.add_ref_delegate(add_ref);
            _self->_base._add_ref = Marshal.GetFunctionPointerForDelegate(_ds0);
            _ds1 = new cef_window_delegate_t.release_delegate(release);
            _self->_base._release = Marshal.GetFunctionPointerForDelegate(_ds1);
            _ds2 = new cef_window_delegate_t.has_one_ref_delegate(has_one_ref);
            _self->_base._has_one_ref = Marshal.GetFunctionPointerForDelegate(_ds2);
            _ds3 = new cef_window_delegate_t.has_at_least_one_ref_delegate(has_at_least_one_ref);
            _self->_base._has_at_least_one_ref = Marshal.GetFunctionPointerForDelegate(_ds3);
            _ds4 = new cef_view_delegate_t.get_preferred_size_delegate(get_preferred_size);
            _self->_get_preferred_size = Marshal.GetFunctionPointerForDelegate(_ds4);
            _ds5 = new cef_view_delegate_t.get_minimum_size_delegate(get_minimum_size);
            _self->_get_minimum_size = Marshal.GetFunctionPointerForDelegate(_ds5);
            _ds6 = new cef_view_delegate_t.get_maximum_size_delegate(get_maximum_size);
            _self->_get_maximum_size = Marshal.GetFunctionPointerForDelegate(_ds6);
            _ds7 = new cef_view_delegate_t.get_height_for_width_delegate(get_height_for_width);
            _self->_get_height_for_width = Marshal.GetFunctionPointerForDelegate(_ds7);
            _ds8 = new cef_view_delegate_t.on_parent_view_changed_delegate(on_parent_view_changed);
            _self->_on_parent_view_changed = Marshal.GetFunctionPointerForDelegate(_ds8);
            _ds9 = new cef_view_delegate_t.on_child_view_changed_delegate(on_child_view_changed);
            _self->_on_child_view_changed = Marshal.GetFunctionPointerForDelegate(_ds9);
            _dsa = new cef_view_delegate_t.on_window_changed_delegate(on_window_changed);
            _self->_on_window_changed = Marshal.GetFunctionPointerForDelegate(_dsa);
            _dsb = new cef_view_delegate_t.on_layout_changed_delegate(on_layout_changed);
            _self->_on_layout_changed = Marshal.GetFunctionPointerForDelegate(_dsb);
            _dsc = new cef_view_delegate_t.on_focus_delegate(on_focus);
            _self->_on_focus = Marshal.GetFunctionPointerForDelegate(_dsc);
            _dsd = new cef_view_delegate_t.on_blur_delegate(on_blur);
            _self->_on_blur = Marshal.GetFunctionPointerForDelegate(_dsd);
            _dse = new cef_view_delegate_t.on_theme_changed_delegate(on_theme_changed);
            _self->_on_theme_changed = Marshal.GetFunctionPointerForDelegate(_dse);
            _dsf = new cef_window_delegate_t.on_window_created_delegate(on_window_created);
            _self->_on_window_created = Marshal.GetFunctionPointerForDelegate(_dsf);
            _ds10 = new cef_window_delegate_t.on_window_closing_delegate(on_window_closing);
            _self->_on_window_closing = Marshal.GetFunctionPointerForDelegate(_ds10);
            _ds11 = new cef_window_delegate_t.on_window_destroyed_delegate(on_window_destroyed);
            _self->_on_window_destroyed = Marshal.GetFunctionPointerForDelegate(_ds11);
            _ds12 = new cef_window_delegate_t.on_window_activation_changed_delegate(on_window_activation_changed);
            _self->_on_window_activation_changed = Marshal.GetFunctionPointerForDelegate(_ds12);
            _ds13 = new cef_window_delegate_t.on_window_bounds_changed_delegate(on_window_bounds_changed);
            _self->_on_window_bounds_changed = Marshal.GetFunctionPointerForDelegate(_ds13);
            _ds14 = new cef_window_delegate_t.on_window_fullscreen_transition_delegate(on_window_fullscreen_transition);
            _self->_on_window_fullscreen_transition = Marshal.GetFunctionPointerForDelegate(_ds14);
            _ds15 = new cef_window_delegate_t.get_parent_window_delegate(get_parent_window);
            _self->_get_parent_window = Marshal.GetFunctionPointerForDelegate(_ds15);
            _ds16 = new cef_window_delegate_t.is_window_modal_dialog_delegate(is_window_modal_dialog);
            _self->_is_window_modal_dialog = Marshal.GetFunctionPointerForDelegate(_ds16);
            _ds17 = new cef_window_delegate_t.get_initial_bounds_delegate(get_initial_bounds);
            _self->_get_initial_bounds = Marshal.GetFunctionPointerForDelegate(_ds17);
            _ds18 = new cef_window_delegate_t.get_initial_show_state_delegate(get_initial_show_state);
            _self->_get_initial_show_state = Marshal.GetFunctionPointerForDelegate(_ds18);
            _ds19 = new cef_window_delegate_t.is_frameless_delegate(is_frameless);
            _self->_is_frameless = Marshal.GetFunctionPointerForDelegate(_ds19);
            _ds1a = new cef_window_delegate_t.with_standard_window_buttons_delegate(with_standard_window_buttons);
            _self->_with_standard_window_buttons = Marshal.GetFunctionPointerForDelegate(_ds1a);
            _ds1b = new cef_window_delegate_t.get_titlebar_height_delegate(get_titlebar_height);
            _self->_get_titlebar_height = Marshal.GetFunctionPointerForDelegate(_ds1b);
            _ds1c = new cef_window_delegate_t.accepts_first_mouse_delegate(accepts_first_mouse);
            _self->_accepts_first_mouse = Marshal.GetFunctionPointerForDelegate(_ds1c);
            _ds1d = new cef_window_delegate_t.can_resize_delegate(can_resize);
            _self->_can_resize = Marshal.GetFunctionPointerForDelegate(_ds1d);
            _ds1e = new cef_window_delegate_t.can_maximize_delegate(can_maximize);
            _self->_can_maximize = Marshal.GetFunctionPointerForDelegate(_ds1e);
            _ds1f = new cef_window_delegate_t.can_minimize_delegate(can_minimize);
            _self->_can_minimize = Marshal.GetFunctionPointerForDelegate(_ds1f);
            _ds20 = new cef_window_delegate_t.can_close_delegate(can_close);
            _self->_can_close = Marshal.GetFunctionPointerForDelegate(_ds20);
            _ds21 = new cef_window_delegate_t.on_accelerator_delegate(on_accelerator);
            _self->_on_accelerator = Marshal.GetFunctionPointerForDelegate(_ds21);
            _ds22 = new cef_window_delegate_t.on_key_event_delegate(on_key_event);
            _self->_on_key_event = Marshal.GetFunctionPointerForDelegate(_ds22);
            _ds23 = new cef_window_delegate_t.on_theme_colors_changed_delegate(on_theme_colors_changed);
            _self->_on_theme_colors_changed = Marshal.GetFunctionPointerForDelegate(_ds23);
            _ds24 = new cef_window_delegate_t.get_window_runtime_style_delegate(get_window_runtime_style);
            _self->_get_window_runtime_style = Marshal.GetFunctionPointerForDelegate(_ds24);
            _ds25 = new cef_window_delegate_t.get_linux_window_properties_delegate(get_linux_window_properties);
            _self->_get_linux_window_properties = Marshal.GetFunctionPointerForDelegate(_ds25);
        }
        
        ~CefWindowDelegate()
        {
            Dispose(false);
        }
        
        protected virtual void Dispose(bool disposing)
        {
            if (_self != null)
            {
                cef_window_delegate_t.Free(_self);
                _self = null;
            }
        }
        
        private void add_ref(cef_window_delegate_t* self)
        {
            lock (SyncRoot)
            {
                var result = ++_refct;
                if (result == 1)
                {
                    lock (_roots) { _roots.Add((IntPtr)_self, this); }
                }
            }
        }
        
        private int release(cef_window_delegate_t* self)
        {
            lock (SyncRoot)
            {
                var result = --_refct;
                if (result == 0)
                {
                    lock (_roots) { _roots.Remove((IntPtr)_self); }
                    return 1;
                }
                return 0;
            }
        }
        
        private int has_one_ref(cef_window_delegate_t* self)
        {
            lock (SyncRoot) { return _refct == 1 ? 1 : 0; }
        }
        
        private int has_at_least_one_ref(cef_window_delegate_t* self)
        {
            lock (SyncRoot) { return _refct != 0 ? 1 : 0; }
        }
        
        internal cef_window_delegate_t* ToNative()
        {
            add_ref(_self);
            return _self;
        }
        
        [Conditional("DEBUG")]
        private void CheckSelf(cef_window_delegate_t* self)
        {
            if (_self != self) throw ExceptionBuilder.InvalidSelfReference();
        }
        
    }
}
