//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Xilium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefWindow : CefPanel
    {
        internal static CefWindow FromNative(cef_window_t* ptr)
        {
            return new CefWindow(ptr);
        }
        
        internal static CefWindow FromNativeOrNull(cef_window_t* ptr)
        {
            if (ptr == null) return null;
            return new CefWindow(ptr);
        }
        
        private CefWindow(cef_window_t* ptr)
            : base((cef_panel_t*)ptr) {}
        
        internal new cef_window_t* ToNative()
        {
            AddRef();
            return (cef_window_t*)_self;
        }
    }
}
