//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_window_delegate_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _get_preferred_size;
        internal IntPtr _get_minimum_size;
        internal IntPtr _get_maximum_size;
        internal IntPtr _get_height_for_width;
        internal IntPtr _on_parent_view_changed;
        internal IntPtr _on_child_view_changed;
        internal IntPtr _on_window_changed;
        internal IntPtr _on_layout_changed;
        internal IntPtr _on_focus;
        internal IntPtr _on_blur;
        internal IntPtr _on_theme_changed;
        internal IntPtr _on_window_created;
        internal IntPtr _on_window_closing;
        internal IntPtr _on_window_destroyed;
        internal IntPtr _on_window_activation_changed;
        internal IntPtr _on_window_bounds_changed;
        internal IntPtr _on_window_fullscreen_transition;
        internal IntPtr _get_parent_window;
        internal IntPtr _is_window_modal_dialog;
        internal IntPtr _get_initial_bounds;
        internal IntPtr _get_initial_show_state;
        internal IntPtr _is_frameless;
        internal IntPtr _with_standard_window_buttons;
        internal IntPtr _get_titlebar_height;
        internal IntPtr _accepts_first_mouse;
        internal IntPtr _can_resize;
        internal IntPtr _can_maximize;
        internal IntPtr _can_minimize;
        internal IntPtr _can_close;
        internal IntPtr _on_accelerator;
        internal IntPtr _on_key_event;
        internal IntPtr _on_theme_colors_changed;
        internal IntPtr _get_window_runtime_style;
        internal IntPtr _get_linux_window_properties;
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void add_ref_delegate(cef_window_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int release_delegate(cef_window_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_one_ref_delegate(cef_window_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_at_least_one_ref_delegate(cef_window_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_preferred_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_minimum_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_maximum_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int get_height_for_width_delegate(cef_view_delegate_t* self, cef_view_t* view, int width);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_parent_view_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added, cef_view_t* parent);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_child_view_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added, cef_view_t* child);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_layout_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, cef_rect_t* new_bounds);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_focus_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_blur_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_theme_changed_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_created_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_closing_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_destroyed_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_activation_changed_delegate(cef_window_delegate_t* self, cef_window_t* window, int active);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_bounds_changed_delegate(cef_window_delegate_t* self, cef_window_t* window, cef_rect_t* new_bounds);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_fullscreen_transition_delegate(cef_window_delegate_t* self, cef_window_t* window, int is_completed);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_window_t* get_parent_window_delegate(cef_window_delegate_t* self, cef_window_t* window, int* is_menu, int* can_activate_menu);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int is_window_modal_dialog_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_rect_t get_initial_bounds_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate CefShowState get_initial_show_state_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int is_frameless_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int with_standard_window_buttons_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int get_titlebar_height_delegate(cef_window_delegate_t* self, cef_window_t* window, float* titlebar_height);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate CefState accepts_first_mouse_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int can_resize_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int can_maximize_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int can_minimize_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int can_close_delegate(cef_window_delegate_t* self, cef_window_t* window);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int on_accelerator_delegate(cef_window_delegate_t* self, cef_window_t* window, int command_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int on_key_event_delegate(cef_window_delegate_t* self, cef_window_t* window, cef_key_event_t* @event);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_theme_colors_changed_delegate(cef_window_delegate_t* self, cef_window_t* window, int chrome_theme);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate CefRuntimeStyle get_window_runtime_style_delegate(cef_window_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int get_linux_window_properties_delegate(cef_window_delegate_t* self, cef_window_t* window, cef_linux_window_properties_t* properties);
        
        private static int _sizeof;
        
        static cef_window_delegate_t()
        {
            _sizeof = Marshal.SizeOf(typeof(cef_window_delegate_t));
        }
        
        internal static cef_window_delegate_t* Alloc()
        {
            var ptr = (cef_window_delegate_t*)Marshal.AllocHGlobal(_sizeof);
            *ptr = new cef_window_delegate_t();
            ptr->_base._size = (UIntPtr)_sizeof;
            return ptr;
        }
        
        internal static void Free(cef_window_delegate_t* ptr)
        {
            Marshal.FreeHGlobal((IntPtr)ptr);
        }
        
    }
}
