//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_panel_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _as_browser_view;
        internal IntPtr _as_button;
        internal IntPtr _as_panel;
        internal IntPtr _as_scroll_view;
        internal IntPtr _as_textfield;
        internal IntPtr _get_type_string;
        internal IntPtr _to_string;
        internal IntPtr _is_valid;
        internal IntPtr _is_attached;
        internal IntPtr _is_same;
        internal IntPtr _get_delegate;
        internal IntPtr _get_window;
        internal IntPtr _get_id;
        internal IntPtr _set_id;
        internal IntPtr _get_group_id;
        internal IntPtr _set_group_id;
        internal IntPtr _get_parent_view;
        internal IntPtr _get_view_for_id;
        internal IntPtr _set_bounds;
        internal IntPtr _get_bounds;
        internal IntPtr _get_bounds_in_screen;
        internal IntPtr _set_size;
        internal IntPtr _get_size;
        internal IntPtr _set_position;
        internal IntPtr _get_position;
        internal IntPtr _set_insets;
        internal IntPtr _get_insets;
        internal IntPtr _get_preferred_size;
        internal IntPtr _size_to_preferred_size;
        internal IntPtr _get_minimum_size;
        internal IntPtr _get_maximum_size;
        internal IntPtr _get_height_for_width;
        internal IntPtr _invalidate_layout;
        internal IntPtr _set_visible;
        internal IntPtr _is_visible;
        internal IntPtr _is_drawn;
        internal IntPtr _set_enabled;
        internal IntPtr _is_enabled;
        internal IntPtr _set_focusable;
        internal IntPtr _is_focusable;
        internal IntPtr _is_accessibility_focusable;
        internal IntPtr _has_focus;
        internal IntPtr _request_focus;
        internal IntPtr _set_background_color;
        internal IntPtr _get_background_color;
        internal IntPtr _get_theme_color;
        internal IntPtr _convert_point_to_screen;
        internal IntPtr _convert_point_from_screen;
        internal IntPtr _convert_point_to_window;
        internal IntPtr _convert_point_from_window;
        internal IntPtr _convert_point_to_view;
        internal IntPtr _convert_point_from_view;
        internal IntPtr _as_window;
        internal IntPtr _set_to_fill_layout;
        internal IntPtr _set_to_box_layout;
        internal IntPtr _get_layout;
        internal IntPtr _layout;
        internal IntPtr _add_child_view;
        internal IntPtr _add_child_view_at;
        internal IntPtr _reorder_child_view;
        internal IntPtr _remove_child_view;
        internal IntPtr _remove_all_child_views;
        internal IntPtr _get_child_view_count;
        internal IntPtr _get_child_view_at;
        
        // CreatePanel
        [DllImport(libcef.DllName, EntryPoint = "cef_panel_create", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_panel_t* create(cef_panel_delegate_t* @delegate);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_ref_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int release_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_one_ref_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_at_least_one_ref_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_browser_view_t* as_browser_view_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_button_t* as_button_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_panel_t* as_panel_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_scroll_view_t* as_scroll_view_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_textfield_t* as_textfield_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_string_userfree* get_type_string_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_string_userfree* to_string_delegate(cef_view_t* self, int include_children);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_valid_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_attached_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_same_delegate(cef_view_t* self, cef_view_t* that);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_view_delegate_t* get_delegate_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_window_t* get_window_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int get_id_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_id_delegate(cef_view_t* self, int id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int get_group_id_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_group_id_delegate(cef_view_t* self, int group_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_view_t* get_parent_view_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_view_t* get_view_for_id_delegate(cef_view_t* self, int id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_bounds_delegate(cef_view_t* self, cef_rect_t* bounds);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_rect_t get_bounds_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_rect_t get_bounds_in_screen_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_size_delegate(cef_view_t* self, cef_size_t* size);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_size_t get_size_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_position_delegate(cef_view_t* self, cef_point_t* position);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_point_t get_position_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_insets_delegate(cef_view_t* self, cef_insets_t* insets);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_insets_t get_insets_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_size_t get_preferred_size_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void size_to_preferred_size_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_size_t get_minimum_size_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_size_t get_maximum_size_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int get_height_for_width_delegate(cef_view_t* self, int width);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void invalidate_layout_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_visible_delegate(cef_view_t* self, int visible);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_visible_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_drawn_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_enabled_delegate(cef_view_t* self, int enabled);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_enabled_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_focusable_delegate(cef_view_t* self, int focusable);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_focusable_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_accessibility_focusable_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_focus_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void request_focus_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_background_color_delegate(cef_view_t* self, uint color);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate uint get_background_color_delegate(cef_view_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate uint get_theme_color_delegate(cef_view_t* self, int color_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int convert_point_to_screen_delegate(cef_view_t* self, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int convert_point_from_screen_delegate(cef_view_t* self, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int convert_point_to_window_delegate(cef_view_t* self, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int convert_point_from_window_delegate(cef_view_t* self, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int convert_point_to_view_delegate(cef_view_t* self, cef_view_t* view, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int convert_point_from_view_delegate(cef_view_t* self, cef_view_t* view, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_window_t* as_window_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_fill_layout_t* set_to_fill_layout_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_box_layout_t* set_to_box_layout_delegate(cef_panel_t* self, cef_box_layout_settings_t* settings);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_layout_t* get_layout_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void layout_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_child_view_delegate(cef_panel_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_child_view_at_delegate(cef_panel_t* self, cef_view_t* view, int index);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void reorder_child_view_delegate(cef_panel_t* self, cef_view_t* view, int index);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void remove_child_view_delegate(cef_panel_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void remove_all_child_views_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate UIntPtr get_child_view_count_delegate(cef_panel_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_view_t* get_child_view_at_delegate(cef_panel_t* self, int index);
        
        // AddRef
        private static IntPtr _p0;
        private static add_ref_delegate _d0;
        
        public static void add_ref(cef_panel_t* self)
        {
            add_ref_delegate d;
            var p = self->_base._add_ref;
            if (p == _p0) { d = _d0; }
            else
            {
                d = (add_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_ref_delegate));
                if (_p0 == IntPtr.Zero) { _d0 = d; _p0 = p; }
            }
            d(self);
        }
        
        // Release
        private static IntPtr _p1;
        private static release_delegate _d1;
        
        public static int release(cef_panel_t* self)
        {
            release_delegate d;
            var p = self->_base._release;
            if (p == _p1) { d = _d1; }
            else
            {
                d = (release_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(release_delegate));
                if (_p1 == IntPtr.Zero) { _d1 = d; _p1 = p; }
            }
            return d(self);
        }
        
        // HasOneRef
        private static IntPtr _p2;
        private static has_one_ref_delegate _d2;
        
        public static int has_one_ref(cef_panel_t* self)
        {
            has_one_ref_delegate d;
            var p = self->_base._has_one_ref;
            if (p == _p2) { d = _d2; }
            else
            {
                d = (has_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_one_ref_delegate));
                if (_p2 == IntPtr.Zero) { _d2 = d; _p2 = p; }
            }
            return d(self);
        }
        
        // HasAtLeastOneRef
        private static IntPtr _p3;
        private static has_at_least_one_ref_delegate _d3;
        
        public static int has_at_least_one_ref(cef_panel_t* self)
        {
            has_at_least_one_ref_delegate d;
            var p = self->_base._has_at_least_one_ref;
            if (p == _p3) { d = _d3; }
            else
            {
                d = (has_at_least_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_at_least_one_ref_delegate));
                if (_p3 == IntPtr.Zero) { _d3 = d; _p3 = p; }
            }
            return d(self);
        }
        
        // AsBrowserView
        private static IntPtr _p4;
        private static as_browser_view_delegate _d4;
        
        public static cef_browser_view_t* as_browser_view(cef_view_t* self)
        {
            as_browser_view_delegate d;
            var p = self->_as_browser_view;
            if (p == _p4) { d = _d4; }
            else
            {
                d = (as_browser_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(as_browser_view_delegate));
                if (_p4 == IntPtr.Zero) { _d4 = d; _p4 = p; }
            }
            return d(self);
        }
        
        // AsButton
        private static IntPtr _p5;
        private static as_button_delegate _d5;
        
        public static cef_button_t* as_button(cef_view_t* self)
        {
            as_button_delegate d;
            var p = self->_as_button;
            if (p == _p5) { d = _d5; }
            else
            {
                d = (as_button_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(as_button_delegate));
                if (_p5 == IntPtr.Zero) { _d5 = d; _p5 = p; }
            }
            return d(self);
        }
        
        // AsPanel
        private static IntPtr _p6;
        private static as_panel_delegate _d6;
        
        public static cef_panel_t* as_panel(cef_view_t* self)
        {
            as_panel_delegate d;
            var p = self->_as_panel;
            if (p == _p6) { d = _d6; }
            else
            {
                d = (as_panel_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(as_panel_delegate));
                if (_p6 == IntPtr.Zero) { _d6 = d; _p6 = p; }
            }
            return d(self);
        }
        
        // AsScrollView
        private static IntPtr _p7;
        private static as_scroll_view_delegate _d7;
        
        public static cef_scroll_view_t* as_scroll_view(cef_view_t* self)
        {
            as_scroll_view_delegate d;
            var p = self->_as_scroll_view;
            if (p == _p7) { d = _d7; }
            else
            {
                d = (as_scroll_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(as_scroll_view_delegate));
                if (_p7 == IntPtr.Zero) { _d7 = d; _p7 = p; }
            }
            return d(self);
        }
        
        // AsTextfield
        private static IntPtr _p8;
        private static as_textfield_delegate _d8;
        
        public static cef_textfield_t* as_textfield(cef_view_t* self)
        {
            as_textfield_delegate d;
            var p = self->_as_textfield;
            if (p == _p8) { d = _d8; }
            else
            {
                d = (as_textfield_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(as_textfield_delegate));
                if (_p8 == IntPtr.Zero) { _d8 = d; _p8 = p; }
            }
            return d(self);
        }
        
        // GetTypeString
        private static IntPtr _p9;
        private static get_type_string_delegate _d9;
        
        public static cef_string_userfree* get_type_string(cef_view_t* self)
        {
            get_type_string_delegate d;
            var p = self->_get_type_string;
            if (p == _p9) { d = _d9; }
            else
            {
                d = (get_type_string_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_type_string_delegate));
                if (_p9 == IntPtr.Zero) { _d9 = d; _p9 = p; }
            }
            return d(self);
        }
        
        // ToString
        private static IntPtr _pa;
        private static to_string_delegate _da;
        
        public static cef_string_userfree* to_string(cef_view_t* self, int include_children)
        {
            to_string_delegate d;
            var p = self->_to_string;
            if (p == _pa) { d = _da; }
            else
            {
                d = (to_string_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(to_string_delegate));
                if (_pa == IntPtr.Zero) { _da = d; _pa = p; }
            }
            return d(self, include_children);
        }
        
        // IsValid
        private static IntPtr _pb;
        private static is_valid_delegate _db;
        
        public static int is_valid(cef_view_t* self)
        {
            is_valid_delegate d;
            var p = self->_is_valid;
            if (p == _pb) { d = _db; }
            else
            {
                d = (is_valid_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_valid_delegate));
                if (_pb == IntPtr.Zero) { _db = d; _pb = p; }
            }
            return d(self);
        }
        
        // IsAttached
        private static IntPtr _pc;
        private static is_attached_delegate _dc;
        
        public static int is_attached(cef_view_t* self)
        {
            is_attached_delegate d;
            var p = self->_is_attached;
            if (p == _pc) { d = _dc; }
            else
            {
                d = (is_attached_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_attached_delegate));
                if (_pc == IntPtr.Zero) { _dc = d; _pc = p; }
            }
            return d(self);
        }
        
        // IsSame
        private static IntPtr _pd;
        private static is_same_delegate _dd;
        
        public static int is_same(cef_view_t* self, cef_view_t* that)
        {
            is_same_delegate d;
            var p = self->_is_same;
            if (p == _pd) { d = _dd; }
            else
            {
                d = (is_same_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_same_delegate));
                if (_pd == IntPtr.Zero) { _dd = d; _pd = p; }
            }
            return d(self, that);
        }
        
        // GetDelegate
        private static IntPtr _pe;
        private static get_delegate_delegate _de;
        
        public static cef_view_delegate_t* get_delegate(cef_view_t* self)
        {
            get_delegate_delegate d;
            var p = self->_get_delegate;
            if (p == _pe) { d = _de; }
            else
            {
                d = (get_delegate_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_delegate_delegate));
                if (_pe == IntPtr.Zero) { _de = d; _pe = p; }
            }
            return d(self);
        }
        
        // GetWindow
        private static IntPtr _pf;
        private static get_window_delegate _df;
        
        public static cef_window_t* get_window(cef_view_t* self)
        {
            get_window_delegate d;
            var p = self->_get_window;
            if (p == _pf) { d = _df; }
            else
            {
                d = (get_window_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_window_delegate));
                if (_pf == IntPtr.Zero) { _df = d; _pf = p; }
            }
            return d(self);
        }
        
        // GetID
        private static IntPtr _p10;
        private static get_id_delegate _d10;
        
        public static int get_id(cef_view_t* self)
        {
            get_id_delegate d;
            var p = self->_get_id;
            if (p == _p10) { d = _d10; }
            else
            {
                d = (get_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_id_delegate));
                if (_p10 == IntPtr.Zero) { _d10 = d; _p10 = p; }
            }
            return d(self);
        }
        
        // SetID
        private static IntPtr _p11;
        private static set_id_delegate _d11;
        
        public static void set_id(cef_view_t* self, int id)
        {
            set_id_delegate d;
            var p = self->_set_id;
            if (p == _p11) { d = _d11; }
            else
            {
                d = (set_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_id_delegate));
                if (_p11 == IntPtr.Zero) { _d11 = d; _p11 = p; }
            }
            d(self, id);
        }
        
        // GetGroupID
        private static IntPtr _p12;
        private static get_group_id_delegate _d12;
        
        public static int get_group_id(cef_view_t* self)
        {
            get_group_id_delegate d;
            var p = self->_get_group_id;
            if (p == _p12) { d = _d12; }
            else
            {
                d = (get_group_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_group_id_delegate));
                if (_p12 == IntPtr.Zero) { _d12 = d; _p12 = p; }
            }
            return d(self);
        }
        
        // SetGroupID
        private static IntPtr _p13;
        private static set_group_id_delegate _d13;
        
        public static void set_group_id(cef_view_t* self, int group_id)
        {
            set_group_id_delegate d;
            var p = self->_set_group_id;
            if (p == _p13) { d = _d13; }
            else
            {
                d = (set_group_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_group_id_delegate));
                if (_p13 == IntPtr.Zero) { _d13 = d; _p13 = p; }
            }
            d(self, group_id);
        }
        
        // GetParentView
        private static IntPtr _p14;
        private static get_parent_view_delegate _d14;
        
        public static cef_view_t* get_parent_view(cef_view_t* self)
        {
            get_parent_view_delegate d;
            var p = self->_get_parent_view;
            if (p == _p14) { d = _d14; }
            else
            {
                d = (get_parent_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_parent_view_delegate));
                if (_p14 == IntPtr.Zero) { _d14 = d; _p14 = p; }
            }
            return d(self);
        }
        
        // GetViewForID
        private static IntPtr _p15;
        private static get_view_for_id_delegate _d15;
        
        public static cef_view_t* get_view_for_id(cef_view_t* self, int id)
        {
            get_view_for_id_delegate d;
            var p = self->_get_view_for_id;
            if (p == _p15) { d = _d15; }
            else
            {
                d = (get_view_for_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_view_for_id_delegate));
                if (_p15 == IntPtr.Zero) { _d15 = d; _p15 = p; }
            }
            return d(self, id);
        }
        
        // SetBounds
        private static IntPtr _p16;
        private static set_bounds_delegate _d16;
        
        public static void set_bounds(cef_view_t* self, cef_rect_t* bounds)
        {
            set_bounds_delegate d;
            var p = self->_set_bounds;
            if (p == _p16) { d = _d16; }
            else
            {
                d = (set_bounds_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_bounds_delegate));
                if (_p16 == IntPtr.Zero) { _d16 = d; _p16 = p; }
            }
            d(self, bounds);
        }
        
        // GetBounds
        private static IntPtr _p17;
        private static get_bounds_delegate _d17;
        
        public static cef_rect_t get_bounds(cef_view_t* self)
        {
            get_bounds_delegate d;
            var p = self->_get_bounds;
            if (p == _p17) { d = _d17; }
            else
            {
                d = (get_bounds_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_bounds_delegate));
                if (_p17 == IntPtr.Zero) { _d17 = d; _p17 = p; }
            }
            return d(self);
        }
        
        // GetBoundsInScreen
        private static IntPtr _p18;
        private static get_bounds_in_screen_delegate _d18;
        
        public static cef_rect_t get_bounds_in_screen(cef_view_t* self)
        {
            get_bounds_in_screen_delegate d;
            var p = self->_get_bounds_in_screen;
            if (p == _p18) { d = _d18; }
            else
            {
                d = (get_bounds_in_screen_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_bounds_in_screen_delegate));
                if (_p18 == IntPtr.Zero) { _d18 = d; _p18 = p; }
            }
            return d(self);
        }
        
        // SetSize
        private static IntPtr _p19;
        private static set_size_delegate _d19;
        
        public static void set_size(cef_view_t* self, cef_size_t* size)
        {
            set_size_delegate d;
            var p = self->_set_size;
            if (p == _p19) { d = _d19; }
            else
            {
                d = (set_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_size_delegate));
                if (_p19 == IntPtr.Zero) { _d19 = d; _p19 = p; }
            }
            d(self, size);
        }
        
        // GetSize
        private static IntPtr _p1a;
        private static get_size_delegate _d1a;
        
        public static cef_size_t get_size(cef_view_t* self)
        {
            get_size_delegate d;
            var p = self->_get_size;
            if (p == _p1a) { d = _d1a; }
            else
            {
                d = (get_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_size_delegate));
                if (_p1a == IntPtr.Zero) { _d1a = d; _p1a = p; }
            }
            return d(self);
        }
        
        // SetPosition
        private static IntPtr _p1b;
        private static set_position_delegate _d1b;
        
        public static void set_position(cef_view_t* self, cef_point_t* position)
        {
            set_position_delegate d;
            var p = self->_set_position;
            if (p == _p1b) { d = _d1b; }
            else
            {
                d = (set_position_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_position_delegate));
                if (_p1b == IntPtr.Zero) { _d1b = d; _p1b = p; }
            }
            d(self, position);
        }
        
        // GetPosition
        private static IntPtr _p1c;
        private static get_position_delegate _d1c;
        
        public static cef_point_t get_position(cef_view_t* self)
        {
            get_position_delegate d;
            var p = self->_get_position;
            if (p == _p1c) { d = _d1c; }
            else
            {
                d = (get_position_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_position_delegate));
                if (_p1c == IntPtr.Zero) { _d1c = d; _p1c = p; }
            }
            return d(self);
        }
        
        // SetInsets
        private static IntPtr _p1d;
        private static set_insets_delegate _d1d;
        
        public static void set_insets(cef_view_t* self, cef_insets_t* insets)
        {
            set_insets_delegate d;
            var p = self->_set_insets;
            if (p == _p1d) { d = _d1d; }
            else
            {
                d = (set_insets_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_insets_delegate));
                if (_p1d == IntPtr.Zero) { _d1d = d; _p1d = p; }
            }
            d(self, insets);
        }
        
        // GetInsets
        private static IntPtr _p1e;
        private static get_insets_delegate _d1e;
        
        public static cef_insets_t get_insets(cef_view_t* self)
        {
            get_insets_delegate d;
            var p = self->_get_insets;
            if (p == _p1e) { d = _d1e; }
            else
            {
                d = (get_insets_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_insets_delegate));
                if (_p1e == IntPtr.Zero) { _d1e = d; _p1e = p; }
            }
            return d(self);
        }
        
        // GetPreferredSize
        private static IntPtr _p1f;
        private static get_preferred_size_delegate _d1f;
        
        public static cef_size_t get_preferred_size(cef_view_t* self)
        {
            get_preferred_size_delegate d;
            var p = self->_get_preferred_size;
            if (p == _p1f) { d = _d1f; }
            else
            {
                d = (get_preferred_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_preferred_size_delegate));
                if (_p1f == IntPtr.Zero) { _d1f = d; _p1f = p; }
            }
            return d(self);
        }
        
        // SizeToPreferredSize
        private static IntPtr _p20;
        private static size_to_preferred_size_delegate _d20;
        
        public static void size_to_preferred_size(cef_view_t* self)
        {
            size_to_preferred_size_delegate d;
            var p = self->_size_to_preferred_size;
            if (p == _p20) { d = _d20; }
            else
            {
                d = (size_to_preferred_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(size_to_preferred_size_delegate));
                if (_p20 == IntPtr.Zero) { _d20 = d; _p20 = p; }
            }
            d(self);
        }
        
        // GetMinimumSize
        private static IntPtr _p21;
        private static get_minimum_size_delegate _d21;
        
        public static cef_size_t get_minimum_size(cef_view_t* self)
        {
            get_minimum_size_delegate d;
            var p = self->_get_minimum_size;
            if (p == _p21) { d = _d21; }
            else
            {
                d = (get_minimum_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_minimum_size_delegate));
                if (_p21 == IntPtr.Zero) { _d21 = d; _p21 = p; }
            }
            return d(self);
        }
        
        // GetMaximumSize
        private static IntPtr _p22;
        private static get_maximum_size_delegate _d22;
        
        public static cef_size_t get_maximum_size(cef_view_t* self)
        {
            get_maximum_size_delegate d;
            var p = self->_get_maximum_size;
            if (p == _p22) { d = _d22; }
            else
            {
                d = (get_maximum_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_maximum_size_delegate));
                if (_p22 == IntPtr.Zero) { _d22 = d; _p22 = p; }
            }
            return d(self);
        }
        
        // GetHeightForWidth
        private static IntPtr _p23;
        private static get_height_for_width_delegate _d23;
        
        public static int get_height_for_width(cef_view_t* self, int width)
        {
            get_height_for_width_delegate d;
            var p = self->_get_height_for_width;
            if (p == _p23) { d = _d23; }
            else
            {
                d = (get_height_for_width_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_height_for_width_delegate));
                if (_p23 == IntPtr.Zero) { _d23 = d; _p23 = p; }
            }
            return d(self, width);
        }
        
        // InvalidateLayout
        private static IntPtr _p24;
        private static invalidate_layout_delegate _d24;
        
        public static void invalidate_layout(cef_view_t* self)
        {
            invalidate_layout_delegate d;
            var p = self->_invalidate_layout;
            if (p == _p24) { d = _d24; }
            else
            {
                d = (invalidate_layout_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(invalidate_layout_delegate));
                if (_p24 == IntPtr.Zero) { _d24 = d; _p24 = p; }
            }
            d(self);
        }
        
        // SetVisible
        private static IntPtr _p25;
        private static set_visible_delegate _d25;
        
        public static void set_visible(cef_view_t* self, int visible)
        {
            set_visible_delegate d;
            var p = self->_set_visible;
            if (p == _p25) { d = _d25; }
            else
            {
                d = (set_visible_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_visible_delegate));
                if (_p25 == IntPtr.Zero) { _d25 = d; _p25 = p; }
            }
            d(self, visible);
        }
        
        // IsVisible
        private static IntPtr _p26;
        private static is_visible_delegate _d26;
        
        public static int is_visible(cef_view_t* self)
        {
            is_visible_delegate d;
            var p = self->_is_visible;
            if (p == _p26) { d = _d26; }
            else
            {
                d = (is_visible_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_visible_delegate));
                if (_p26 == IntPtr.Zero) { _d26 = d; _p26 = p; }
            }
            return d(self);
        }
        
        // IsDrawn
        private static IntPtr _p27;
        private static is_drawn_delegate _d27;
        
        public static int is_drawn(cef_view_t* self)
        {
            is_drawn_delegate d;
            var p = self->_is_drawn;
            if (p == _p27) { d = _d27; }
            else
            {
                d = (is_drawn_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_drawn_delegate));
                if (_p27 == IntPtr.Zero) { _d27 = d; _p27 = p; }
            }
            return d(self);
        }
        
        // SetEnabled
        private static IntPtr _p28;
        private static set_enabled_delegate _d28;
        
        public static void set_enabled(cef_view_t* self, int enabled)
        {
            set_enabled_delegate d;
            var p = self->_set_enabled;
            if (p == _p28) { d = _d28; }
            else
            {
                d = (set_enabled_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_enabled_delegate));
                if (_p28 == IntPtr.Zero) { _d28 = d; _p28 = p; }
            }
            d(self, enabled);
        }
        
        // IsEnabled
        private static IntPtr _p29;
        private static is_enabled_delegate _d29;
        
        public static int is_enabled(cef_view_t* self)
        {
            is_enabled_delegate d;
            var p = self->_is_enabled;
            if (p == _p29) { d = _d29; }
            else
            {
                d = (is_enabled_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_enabled_delegate));
                if (_p29 == IntPtr.Zero) { _d29 = d; _p29 = p; }
            }
            return d(self);
        }
        
        // SetFocusable
        private static IntPtr _p2a;
        private static set_focusable_delegate _d2a;
        
        public static void set_focusable(cef_view_t* self, int focusable)
        {
            set_focusable_delegate d;
            var p = self->_set_focusable;
            if (p == _p2a) { d = _d2a; }
            else
            {
                d = (set_focusable_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_focusable_delegate));
                if (_p2a == IntPtr.Zero) { _d2a = d; _p2a = p; }
            }
            d(self, focusable);
        }
        
        // IsFocusable
        private static IntPtr _p2b;
        private static is_focusable_delegate _d2b;
        
        public static int is_focusable(cef_view_t* self)
        {
            is_focusable_delegate d;
            var p = self->_is_focusable;
            if (p == _p2b) { d = _d2b; }
            else
            {
                d = (is_focusable_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_focusable_delegate));
                if (_p2b == IntPtr.Zero) { _d2b = d; _p2b = p; }
            }
            return d(self);
        }
        
        // IsAccessibilityFocusable
        private static IntPtr _p2c;
        private static is_accessibility_focusable_delegate _d2c;
        
        public static int is_accessibility_focusable(cef_view_t* self)
        {
            is_accessibility_focusable_delegate d;
            var p = self->_is_accessibility_focusable;
            if (p == _p2c) { d = _d2c; }
            else
            {
                d = (is_accessibility_focusable_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_accessibility_focusable_delegate));
                if (_p2c == IntPtr.Zero) { _d2c = d; _p2c = p; }
            }
            return d(self);
        }
        
        // HasFocus
        private static IntPtr _p2d;
        private static has_focus_delegate _d2d;
        
        public static int has_focus(cef_view_t* self)
        {
            has_focus_delegate d;
            var p = self->_has_focus;
            if (p == _p2d) { d = _d2d; }
            else
            {
                d = (has_focus_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_focus_delegate));
                if (_p2d == IntPtr.Zero) { _d2d = d; _p2d = p; }
            }
            return d(self);
        }
        
        // RequestFocus
        private static IntPtr _p2e;
        private static request_focus_delegate _d2e;
        
        public static void request_focus(cef_view_t* self)
        {
            request_focus_delegate d;
            var p = self->_request_focus;
            if (p == _p2e) { d = _d2e; }
            else
            {
                d = (request_focus_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(request_focus_delegate));
                if (_p2e == IntPtr.Zero) { _d2e = d; _p2e = p; }
            }
            d(self);
        }
        
        // SetBackgroundColor
        private static IntPtr _p2f;
        private static set_background_color_delegate _d2f;
        
        public static void set_background_color(cef_view_t* self, uint color)
        {
            set_background_color_delegate d;
            var p = self->_set_background_color;
            if (p == _p2f) { d = _d2f; }
            else
            {
                d = (set_background_color_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_background_color_delegate));
                if (_p2f == IntPtr.Zero) { _d2f = d; _p2f = p; }
            }
            d(self, color);
        }
        
        // GetBackgroundColor
        private static IntPtr _p30;
        private static get_background_color_delegate _d30;
        
        public static uint get_background_color(cef_view_t* self)
        {
            get_background_color_delegate d;
            var p = self->_get_background_color;
            if (p == _p30) { d = _d30; }
            else
            {
                d = (get_background_color_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_background_color_delegate));
                if (_p30 == IntPtr.Zero) { _d30 = d; _p30 = p; }
            }
            return d(self);
        }
        
        // GetThemeColor
        private static IntPtr _p31;
        private static get_theme_color_delegate _d31;
        
        public static uint get_theme_color(cef_view_t* self, int color_id)
        {
            get_theme_color_delegate d;
            var p = self->_get_theme_color;
            if (p == _p31) { d = _d31; }
            else
            {
                d = (get_theme_color_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_theme_color_delegate));
                if (_p31 == IntPtr.Zero) { _d31 = d; _p31 = p; }
            }
            return d(self, color_id);
        }
        
        // ConvertPointToScreen
        private static IntPtr _p32;
        private static convert_point_to_screen_delegate _d32;
        
        public static int convert_point_to_screen(cef_view_t* self, cef_point_t* point)
        {
            convert_point_to_screen_delegate d;
            var p = self->_convert_point_to_screen;
            if (p == _p32) { d = _d32; }
            else
            {
                d = (convert_point_to_screen_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_to_screen_delegate));
                if (_p32 == IntPtr.Zero) { _d32 = d; _p32 = p; }
            }
            return d(self, point);
        }
        
        // ConvertPointFromScreen
        private static IntPtr _p33;
        private static convert_point_from_screen_delegate _d33;
        
        public static int convert_point_from_screen(cef_view_t* self, cef_point_t* point)
        {
            convert_point_from_screen_delegate d;
            var p = self->_convert_point_from_screen;
            if (p == _p33) { d = _d33; }
            else
            {
                d = (convert_point_from_screen_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_from_screen_delegate));
                if (_p33 == IntPtr.Zero) { _d33 = d; _p33 = p; }
            }
            return d(self, point);
        }
        
        // ConvertPointToWindow
        private static IntPtr _p34;
        private static convert_point_to_window_delegate _d34;
        
        public static int convert_point_to_window(cef_view_t* self, cef_point_t* point)
        {
            convert_point_to_window_delegate d;
            var p = self->_convert_point_to_window;
            if (p == _p34) { d = _d34; }
            else
            {
                d = (convert_point_to_window_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_to_window_delegate));
                if (_p34 == IntPtr.Zero) { _d34 = d; _p34 = p; }
            }
            return d(self, point);
        }
        
        // ConvertPointFromWindow
        private static IntPtr _p35;
        private static convert_point_from_window_delegate _d35;
        
        public static int convert_point_from_window(cef_view_t* self, cef_point_t* point)
        {
            convert_point_from_window_delegate d;
            var p = self->_convert_point_from_window;
            if (p == _p35) { d = _d35; }
            else
            {
                d = (convert_point_from_window_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_from_window_delegate));
                if (_p35 == IntPtr.Zero) { _d35 = d; _p35 = p; }
            }
            return d(self, point);
        }
        
        // ConvertPointToView
        private static IntPtr _p36;
        private static convert_point_to_view_delegate _d36;
        
        public static int convert_point_to_view(cef_view_t* self, cef_view_t* view, cef_point_t* point)
        {
            convert_point_to_view_delegate d;
            var p = self->_convert_point_to_view;
            if (p == _p36) { d = _d36; }
            else
            {
                d = (convert_point_to_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_to_view_delegate));
                if (_p36 == IntPtr.Zero) { _d36 = d; _p36 = p; }
            }
            return d(self, view, point);
        }
        
        // ConvertPointFromView
        private static IntPtr _p37;
        private static convert_point_from_view_delegate _d37;
        
        public static int convert_point_from_view(cef_view_t* self, cef_view_t* view, cef_point_t* point)
        {
            convert_point_from_view_delegate d;
            var p = self->_convert_point_from_view;
            if (p == _p37) { d = _d37; }
            else
            {
                d = (convert_point_from_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_from_view_delegate));
                if (_p37 == IntPtr.Zero) { _d37 = d; _p37 = p; }
            }
            return d(self, view, point);
        }
        
        // AsWindow
        private static IntPtr _p38;
        private static as_window_delegate _d38;
        
        public static cef_window_t* as_window(cef_panel_t* self)
        {
            as_window_delegate d;
            var p = self->_as_window;
            if (p == _p38) { d = _d38; }
            else
            {
                d = (as_window_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(as_window_delegate));
                if (_p38 == IntPtr.Zero) { _d38 = d; _p38 = p; }
            }
            return d(self);
        }
        
        // SetToFillLayout
        private static IntPtr _p39;
        private static set_to_fill_layout_delegate _d39;
        
        public static cef_fill_layout_t* set_to_fill_layout(cef_panel_t* self)
        {
            set_to_fill_layout_delegate d;
            var p = self->_set_to_fill_layout;
            if (p == _p39) { d = _d39; }
            else
            {
                d = (set_to_fill_layout_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_to_fill_layout_delegate));
                if (_p39 == IntPtr.Zero) { _d39 = d; _p39 = p; }
            }
            return d(self);
        }
        
        // SetToBoxLayout
        private static IntPtr _p3a;
        private static set_to_box_layout_delegate _d3a;
        
        public static cef_box_layout_t* set_to_box_layout(cef_panel_t* self, cef_box_layout_settings_t* settings)
        {
            set_to_box_layout_delegate d;
            var p = self->_set_to_box_layout;
            if (p == _p3a) { d = _d3a; }
            else
            {
                d = (set_to_box_layout_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_to_box_layout_delegate));
                if (_p3a == IntPtr.Zero) { _d3a = d; _p3a = p; }
            }
            return d(self, settings);
        }
        
        // GetLayout
        private static IntPtr _p3b;
        private static get_layout_delegate _d3b;
        
        public static cef_layout_t* get_layout(cef_panel_t* self)
        {
            get_layout_delegate d;
            var p = self->_get_layout;
            if (p == _p3b) { d = _d3b; }
            else
            {
                d = (get_layout_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_layout_delegate));
                if (_p3b == IntPtr.Zero) { _d3b = d; _p3b = p; }
            }
            return d(self);
        }
        
        // Layout
        private static IntPtr _p3c;
        private static layout_delegate _d3c;
        
        public static void layout(cef_panel_t* self)
        {
            layout_delegate d;
            var p = self->_layout;
            if (p == _p3c) { d = _d3c; }
            else
            {
                d = (layout_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(layout_delegate));
                if (_p3c == IntPtr.Zero) { _d3c = d; _p3c = p; }
            }
            d(self);
        }
        
        // AddChildView
        private static IntPtr _p3d;
        private static add_child_view_delegate _d3d;
        
        public static void add_child_view(cef_panel_t* self, cef_view_t* view)
        {
            add_child_view_delegate d;
            var p = self->_add_child_view;
            if (p == _p3d) { d = _d3d; }
            else
            {
                d = (add_child_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_child_view_delegate));
                if (_p3d == IntPtr.Zero) { _d3d = d; _p3d = p; }
            }
            d(self, view);
        }
        
        // AddChildViewAt
        private static IntPtr _p3e;
        private static add_child_view_at_delegate _d3e;
        
        public static void add_child_view_at(cef_panel_t* self, cef_view_t* view, int index)
        {
            add_child_view_at_delegate d;
            var p = self->_add_child_view_at;
            if (p == _p3e) { d = _d3e; }
            else
            {
                d = (add_child_view_at_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_child_view_at_delegate));
                if (_p3e == IntPtr.Zero) { _d3e = d; _p3e = p; }
            }
            d(self, view, index);
        }
        
        // ReorderChildView
        private static IntPtr _p3f;
        private static reorder_child_view_delegate _d3f;
        
        public static void reorder_child_view(cef_panel_t* self, cef_view_t* view, int index)
        {
            reorder_child_view_delegate d;
            var p = self->_reorder_child_view;
            if (p == _p3f) { d = _d3f; }
            else
            {
                d = (reorder_child_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(reorder_child_view_delegate));
                if (_p3f == IntPtr.Zero) { _d3f = d; _p3f = p; }
            }
            d(self, view, index);
        }
        
        // RemoveChildView
        private static IntPtr _p40;
        private static remove_child_view_delegate _d40;
        
        public static void remove_child_view(cef_panel_t* self, cef_view_t* view)
        {
            remove_child_view_delegate d;
            var p = self->_remove_child_view;
            if (p == _p40) { d = _d40; }
            else
            {
                d = (remove_child_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(remove_child_view_delegate));
                if (_p40 == IntPtr.Zero) { _d40 = d; _p40 = p; }
            }
            d(self, view);
        }
        
        // RemoveAllChildViews
        private static IntPtr _p41;
        private static remove_all_child_views_delegate _d41;
        
        public static void remove_all_child_views(cef_panel_t* self)
        {
            remove_all_child_views_delegate d;
            var p = self->_remove_all_child_views;
            if (p == _p41) { d = _d41; }
            else
            {
                d = (remove_all_child_views_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(remove_all_child_views_delegate));
                if (_p41 == IntPtr.Zero) { _d41 = d; _p41 = p; }
            }
            d(self);
        }
        
        // GetChildViewCount
        private static IntPtr _p42;
        private static get_child_view_count_delegate _d42;
        
        public static UIntPtr get_child_view_count(cef_panel_t* self)
        {
            get_child_view_count_delegate d;
            var p = self->_get_child_view_count;
            if (p == _p42) { d = _d42; }
            else
            {
                d = (get_child_view_count_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_child_view_count_delegate));
                if (_p42 == IntPtr.Zero) { _d42 = d; _p42 = p; }
            }
            return d(self);
        }
        
        // GetChildViewAt
        private static IntPtr _p43;
        private static get_child_view_at_delegate _d43;
        
        public static cef_view_t* get_child_view_at(cef_panel_t* self, int index)
        {
            get_child_view_at_delegate d;
            var p = self->_get_child_view_at;
            if (p == _p43) { d = _d43; }
            else
            {
                d = (get_child_view_at_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_child_view_at_delegate));
                if (_p43 == IntPtr.Zero) { _d43 = d; _p43 = p; }
            }
            return d(self, index);
        }
        
    }
}
