//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_overlay_controller_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _is_valid;
        internal IntPtr _is_same;
        internal IntPtr _get_contents_view;
        internal IntPtr _get_window;
        internal IntPtr _get_docking_mode;
        internal IntPtr _destroy;
        internal IntPtr _set_bounds;
        internal IntPtr _get_bounds;
        internal IntPtr _get_bounds_in_screen;
        internal IntPtr _set_size;
        internal IntPtr _get_size;
        internal IntPtr _set_position;
        internal IntPtr _get_position;
        internal IntPtr _set_insets;
        internal IntPtr _get_insets;
        internal IntPtr _size_to_preferred_size;
        internal IntPtr _set_visible;
        internal IntPtr _is_visible;
        internal IntPtr _is_drawn;
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_ref_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int release_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_one_ref_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_at_least_one_ref_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_valid_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_same_delegate(cef_overlay_controller_t* self, cef_overlay_controller_t* that);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_view_t* get_contents_view_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_window_t* get_window_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate CefDockingMode get_docking_mode_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void destroy_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_bounds_delegate(cef_overlay_controller_t* self, cef_rect_t* bounds);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_rect_t get_bounds_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_rect_t get_bounds_in_screen_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_size_delegate(cef_overlay_controller_t* self, cef_size_t* size);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_size_t get_size_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_position_delegate(cef_overlay_controller_t* self, cef_point_t* position);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_point_t get_position_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_insets_delegate(cef_overlay_controller_t* self, cef_insets_t* insets);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_insets_t get_insets_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void size_to_preferred_size_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void set_visible_delegate(cef_overlay_controller_t* self, int visible);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_visible_delegate(cef_overlay_controller_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int is_drawn_delegate(cef_overlay_controller_t* self);
        
        // AddRef
        private static IntPtr _p0;
        private static add_ref_delegate _d0;
        
        public static void add_ref(cef_overlay_controller_t* self)
        {
            add_ref_delegate d;
            var p = self->_base._add_ref;
            if (p == _p0) { d = _d0; }
            else
            {
                d = (add_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_ref_delegate));
                if (_p0 == IntPtr.Zero) { _d0 = d; _p0 = p; }
            }
            d(self);
        }
        
        // Release
        private static IntPtr _p1;
        private static release_delegate _d1;
        
        public static int release(cef_overlay_controller_t* self)
        {
            release_delegate d;
            var p = self->_base._release;
            if (p == _p1) { d = _d1; }
            else
            {
                d = (release_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(release_delegate));
                if (_p1 == IntPtr.Zero) { _d1 = d; _p1 = p; }
            }
            return d(self);
        }
        
        // HasOneRef
        private static IntPtr _p2;
        private static has_one_ref_delegate _d2;
        
        public static int has_one_ref(cef_overlay_controller_t* self)
        {
            has_one_ref_delegate d;
            var p = self->_base._has_one_ref;
            if (p == _p2) { d = _d2; }
            else
            {
                d = (has_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_one_ref_delegate));
                if (_p2 == IntPtr.Zero) { _d2 = d; _p2 = p; }
            }
            return d(self);
        }
        
        // HasAtLeastOneRef
        private static IntPtr _p3;
        private static has_at_least_one_ref_delegate _d3;
        
        public static int has_at_least_one_ref(cef_overlay_controller_t* self)
        {
            has_at_least_one_ref_delegate d;
            var p = self->_base._has_at_least_one_ref;
            if (p == _p3) { d = _d3; }
            else
            {
                d = (has_at_least_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_at_least_one_ref_delegate));
                if (_p3 == IntPtr.Zero) { _d3 = d; _p3 = p; }
            }
            return d(self);
        }
        
        // IsValid
        private static IntPtr _p4;
        private static is_valid_delegate _d4;
        
        public static int is_valid(cef_overlay_controller_t* self)
        {
            is_valid_delegate d;
            var p = self->_is_valid;
            if (p == _p4) { d = _d4; }
            else
            {
                d = (is_valid_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_valid_delegate));
                if (_p4 == IntPtr.Zero) { _d4 = d; _p4 = p; }
            }
            return d(self);
        }
        
        // IsSame
        private static IntPtr _p5;
        private static is_same_delegate _d5;
        
        public static int is_same(cef_overlay_controller_t* self, cef_overlay_controller_t* that)
        {
            is_same_delegate d;
            var p = self->_is_same;
            if (p == _p5) { d = _d5; }
            else
            {
                d = (is_same_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_same_delegate));
                if (_p5 == IntPtr.Zero) { _d5 = d; _p5 = p; }
            }
            return d(self, that);
        }
        
        // GetContentsView
        private static IntPtr _p6;
        private static get_contents_view_delegate _d6;
        
        public static cef_view_t* get_contents_view(cef_overlay_controller_t* self)
        {
            get_contents_view_delegate d;
            var p = self->_get_contents_view;
            if (p == _p6) { d = _d6; }
            else
            {
                d = (get_contents_view_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_contents_view_delegate));
                if (_p6 == IntPtr.Zero) { _d6 = d; _p6 = p; }
            }
            return d(self);
        }
        
        // GetWindow
        private static IntPtr _p7;
        private static get_window_delegate _d7;
        
        public static cef_window_t* get_window(cef_overlay_controller_t* self)
        {
            get_window_delegate d;
            var p = self->_get_window;
            if (p == _p7) { d = _d7; }
            else
            {
                d = (get_window_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_window_delegate));
                if (_p7 == IntPtr.Zero) { _d7 = d; _p7 = p; }
            }
            return d(self);
        }
        
        // GetDockingMode
        private static IntPtr _p8;
        private static get_docking_mode_delegate _d8;
        
        public static CefDockingMode get_docking_mode(cef_overlay_controller_t* self)
        {
            get_docking_mode_delegate d;
            var p = self->_get_docking_mode;
            if (p == _p8) { d = _d8; }
            else
            {
                d = (get_docking_mode_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_docking_mode_delegate));
                if (_p8 == IntPtr.Zero) { _d8 = d; _p8 = p; }
            }
            return d(self);
        }
        
        // Destroy
        private static IntPtr _p9;
        private static destroy_delegate _d9;
        
        public static void destroy(cef_overlay_controller_t* self)
        {
            destroy_delegate d;
            var p = self->_destroy;
            if (p == _p9) { d = _d9; }
            else
            {
                d = (destroy_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(destroy_delegate));
                if (_p9 == IntPtr.Zero) { _d9 = d; _p9 = p; }
            }
            d(self);
        }
        
        // SetBounds
        private static IntPtr _pa;
        private static set_bounds_delegate _da;
        
        public static void set_bounds(cef_overlay_controller_t* self, cef_rect_t* bounds)
        {
            set_bounds_delegate d;
            var p = self->_set_bounds;
            if (p == _pa) { d = _da; }
            else
            {
                d = (set_bounds_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_bounds_delegate));
                if (_pa == IntPtr.Zero) { _da = d; _pa = p; }
            }
            d(self, bounds);
        }
        
        // GetBounds
        private static IntPtr _pb;
        private static get_bounds_delegate _db;
        
        public static cef_rect_t get_bounds(cef_overlay_controller_t* self)
        {
            get_bounds_delegate d;
            var p = self->_get_bounds;
            if (p == _pb) { d = _db; }
            else
            {
                d = (get_bounds_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_bounds_delegate));
                if (_pb == IntPtr.Zero) { _db = d; _pb = p; }
            }
            return d(self);
        }
        
        // GetBoundsInScreen
        private static IntPtr _pc;
        private static get_bounds_in_screen_delegate _dc;
        
        public static cef_rect_t get_bounds_in_screen(cef_overlay_controller_t* self)
        {
            get_bounds_in_screen_delegate d;
            var p = self->_get_bounds_in_screen;
            if (p == _pc) { d = _dc; }
            else
            {
                d = (get_bounds_in_screen_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_bounds_in_screen_delegate));
                if (_pc == IntPtr.Zero) { _dc = d; _pc = p; }
            }
            return d(self);
        }
        
        // SetSize
        private static IntPtr _pd;
        private static set_size_delegate _dd;
        
        public static void set_size(cef_overlay_controller_t* self, cef_size_t* size)
        {
            set_size_delegate d;
            var p = self->_set_size;
            if (p == _pd) { d = _dd; }
            else
            {
                d = (set_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_size_delegate));
                if (_pd == IntPtr.Zero) { _dd = d; _pd = p; }
            }
            d(self, size);
        }
        
        // GetSize
        private static IntPtr _pe;
        private static get_size_delegate _de;
        
        public static cef_size_t get_size(cef_overlay_controller_t* self)
        {
            get_size_delegate d;
            var p = self->_get_size;
            if (p == _pe) { d = _de; }
            else
            {
                d = (get_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_size_delegate));
                if (_pe == IntPtr.Zero) { _de = d; _pe = p; }
            }
            return d(self);
        }
        
        // SetPosition
        private static IntPtr _pf;
        private static set_position_delegate _df;
        
        public static void set_position(cef_overlay_controller_t* self, cef_point_t* position)
        {
            set_position_delegate d;
            var p = self->_set_position;
            if (p == _pf) { d = _df; }
            else
            {
                d = (set_position_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_position_delegate));
                if (_pf == IntPtr.Zero) { _df = d; _pf = p; }
            }
            d(self, position);
        }
        
        // GetPosition
        private static IntPtr _p10;
        private static get_position_delegate _d10;
        
        public static cef_point_t get_position(cef_overlay_controller_t* self)
        {
            get_position_delegate d;
            var p = self->_get_position;
            if (p == _p10) { d = _d10; }
            else
            {
                d = (get_position_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_position_delegate));
                if (_p10 == IntPtr.Zero) { _d10 = d; _p10 = p; }
            }
            return d(self);
        }
        
        // SetInsets
        private static IntPtr _p11;
        private static set_insets_delegate _d11;
        
        public static void set_insets(cef_overlay_controller_t* self, cef_insets_t* insets)
        {
            set_insets_delegate d;
            var p = self->_set_insets;
            if (p == _p11) { d = _d11; }
            else
            {
                d = (set_insets_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_insets_delegate));
                if (_p11 == IntPtr.Zero) { _d11 = d; _p11 = p; }
            }
            d(self, insets);
        }
        
        // GetInsets
        private static IntPtr _p12;
        private static get_insets_delegate _d12;
        
        public static cef_insets_t get_insets(cef_overlay_controller_t* self)
        {
            get_insets_delegate d;
            var p = self->_get_insets;
            if (p == _p12) { d = _d12; }
            else
            {
                d = (get_insets_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_insets_delegate));
                if (_p12 == IntPtr.Zero) { _d12 = d; _p12 = p; }
            }
            return d(self);
        }
        
        // SizeToPreferredSize
        private static IntPtr _p13;
        private static size_to_preferred_size_delegate _d13;
        
        public static void size_to_preferred_size(cef_overlay_controller_t* self)
        {
            size_to_preferred_size_delegate d;
            var p = self->_size_to_preferred_size;
            if (p == _p13) { d = _d13; }
            else
            {
                d = (size_to_preferred_size_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(size_to_preferred_size_delegate));
                if (_p13 == IntPtr.Zero) { _d13 = d; _p13 = p; }
            }
            d(self);
        }
        
        // SetVisible
        private static IntPtr _p14;
        private static set_visible_delegate _d14;
        
        public static void set_visible(cef_overlay_controller_t* self, int visible)
        {
            set_visible_delegate d;
            var p = self->_set_visible;
            if (p == _p14) { d = _d14; }
            else
            {
                d = (set_visible_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(set_visible_delegate));
                if (_p14 == IntPtr.Zero) { _d14 = d; _p14 = p; }
            }
            d(self, visible);
        }
        
        // IsVisible
        private static IntPtr _p15;
        private static is_visible_delegate _d15;
        
        public static int is_visible(cef_overlay_controller_t* self)
        {
            is_visible_delegate d;
            var p = self->_is_visible;
            if (p == _p15) { d = _d15; }
            else
            {
                d = (is_visible_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_visible_delegate));
                if (_p15 == IntPtr.Zero) { _d15 = d; _p15 = p; }
            }
            return d(self);
        }
        
        // IsDrawn
        private static IntPtr _p16;
        private static is_drawn_delegate _d16;
        
        public static int is_drawn(cef_overlay_controller_t* self)
        {
            is_drawn_delegate d;
            var p = self->_is_drawn;
            if (p == _p16) { d = _d16; }
            else
            {
                d = (is_drawn_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(is_drawn_delegate));
                if (_p16 == IntPtr.Zero) { _d16 = d; _p16 = p; }
            }
            return d(self);
        }
        
    }
}
