//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_display_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _get_id;
        internal IntPtr _get_device_scale_factor;
        internal IntPtr _convert_point_to_pixels;
        internal IntPtr _convert_point_from_pixels;
        internal IntPtr _get_bounds;
        internal IntPtr _get_work_area;
        internal IntPtr _get_rotation;
        
        // GetPrimaryDisplay
        [DllImport(libcef.DllName, EntryPoint = "cef_display_get_primary", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_display_t* get_primary();
        
        // GetDisplayNearestPoint
        [DllImport(libcef.DllName, EntryPoint = "cef_display_get_nearest_point", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_display_t* get(cef_point_t* point, int input_pixel_coords);
        
        // GetDisplayMatchingBounds
        [DllImport(libcef.DllName, EntryPoint = "cef_display_get_matching_bounds", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_display_t* get(cef_rect_t* bounds, int input_pixel_coords);
        
        // GetDisplayCount
        [DllImport(libcef.DllName, EntryPoint = "cef_display_get_count", CallingConvention = libcef.CEF_CALL)]
        public static extern UIntPtr get();
        
        // GetAllDisplays
        [DllImport(libcef.DllName, EntryPoint = "cef_display_get_alls", CallingConvention = libcef.CEF_CALL)]
        public static extern void get_all(UIntPtr* displaysCount, cef_display_t** displays);
        
        // ConvertScreenPointToPixels
        [DllImport(libcef.DllName, EntryPoint = "cef_display_convert_screen_point_to_pixels", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_point_t convert_screen_point_to_pixels(cef_point_t* point);
        
        // ConvertScreenPointFromPixels
        [DllImport(libcef.DllName, EntryPoint = "cef_display_convert_screen_point_from_pixels", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_point_t convert_screen_point_from_pixels(cef_point_t* point);
        
        // ConvertScreenRectToPixels
        [DllImport(libcef.DllName, EntryPoint = "cef_display_convert_screen_rect_to_pixels", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_rect_t convert_screen_rect_to_pixels(cef_rect_t* rect);
        
        // ConvertScreenRectFromPixels
        [DllImport(libcef.DllName, EntryPoint = "cef_display_convert_screen_rect_from_pixels", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_rect_t convert_screen_rect_from_pixels(cef_rect_t* rect);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_ref_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int release_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_one_ref_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_at_least_one_ref_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate long get_id_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate float get_device_scale_factor_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void convert_point_to_pixels_delegate(cef_display_t* self, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void convert_point_from_pixels_delegate(cef_display_t* self, cef_point_t* point);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_rect_t get_bounds_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_rect_t get_work_area_delegate(cef_display_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int get_rotation_delegate(cef_display_t* self);
        
        // AddRef
        private static IntPtr _p0;
        private static add_ref_delegate _d0;
        
        public static void add_ref(cef_display_t* self)
        {
            add_ref_delegate d;
            var p = self->_base._add_ref;
            if (p == _p0) { d = _d0; }
            else
            {
                d = (add_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_ref_delegate));
                if (_p0 == IntPtr.Zero) { _d0 = d; _p0 = p; }
            }
            d(self);
        }
        
        // Release
        private static IntPtr _p1;
        private static release_delegate _d1;
        
        public static int release(cef_display_t* self)
        {
            release_delegate d;
            var p = self->_base._release;
            if (p == _p1) { d = _d1; }
            else
            {
                d = (release_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(release_delegate));
                if (_p1 == IntPtr.Zero) { _d1 = d; _p1 = p; }
            }
            return d(self);
        }
        
        // HasOneRef
        private static IntPtr _p2;
        private static has_one_ref_delegate _d2;
        
        public static int has_one_ref(cef_display_t* self)
        {
            has_one_ref_delegate d;
            var p = self->_base._has_one_ref;
            if (p == _p2) { d = _d2; }
            else
            {
                d = (has_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_one_ref_delegate));
                if (_p2 == IntPtr.Zero) { _d2 = d; _p2 = p; }
            }
            return d(self);
        }
        
        // HasAtLeastOneRef
        private static IntPtr _p3;
        private static has_at_least_one_ref_delegate _d3;
        
        public static int has_at_least_one_ref(cef_display_t* self)
        {
            has_at_least_one_ref_delegate d;
            var p = self->_base._has_at_least_one_ref;
            if (p == _p3) { d = _d3; }
            else
            {
                d = (has_at_least_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_at_least_one_ref_delegate));
                if (_p3 == IntPtr.Zero) { _d3 = d; _p3 = p; }
            }
            return d(self);
        }
        
        // GetID
        private static IntPtr _p4;
        private static get_id_delegate _d4;
        
        public static long get_id(cef_display_t* self)
        {
            get_id_delegate d;
            var p = self->_get_id;
            if (p == _p4) { d = _d4; }
            else
            {
                d = (get_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_id_delegate));
                if (_p4 == IntPtr.Zero) { _d4 = d; _p4 = p; }
            }
            return d(self);
        }
        
        // GetDeviceScaleFactor
        private static IntPtr _p5;
        private static get_device_scale_factor_delegate _d5;
        
        public static float get_device_scale_factor(cef_display_t* self)
        {
            get_device_scale_factor_delegate d;
            var p = self->_get_device_scale_factor;
            if (p == _p5) { d = _d5; }
            else
            {
                d = (get_device_scale_factor_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_device_scale_factor_delegate));
                if (_p5 == IntPtr.Zero) { _d5 = d; _p5 = p; }
            }
            return d(self);
        }
        
        // ConvertPointToPixels
        private static IntPtr _p6;
        private static convert_point_to_pixels_delegate _d6;
        
        public static void convert_point_to_pixels(cef_display_t* self, cef_point_t* point)
        {
            convert_point_to_pixels_delegate d;
            var p = self->_convert_point_to_pixels;
            if (p == _p6) { d = _d6; }
            else
            {
                d = (convert_point_to_pixels_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_to_pixels_delegate));
                if (_p6 == IntPtr.Zero) { _d6 = d; _p6 = p; }
            }
            d(self, point);
        }
        
        // ConvertPointFromPixels
        private static IntPtr _p7;
        private static convert_point_from_pixels_delegate _d7;
        
        public static void convert_point_from_pixels(cef_display_t* self, cef_point_t* point)
        {
            convert_point_from_pixels_delegate d;
            var p = self->_convert_point_from_pixels;
            if (p == _p7) { d = _d7; }
            else
            {
                d = (convert_point_from_pixels_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(convert_point_from_pixels_delegate));
                if (_p7 == IntPtr.Zero) { _d7 = d; _p7 = p; }
            }
            d(self, point);
        }
        
        // GetBounds
        private static IntPtr _p8;
        private static get_bounds_delegate _d8;
        
        public static cef_rect_t get_bounds(cef_display_t* self)
        {
            get_bounds_delegate d;
            var p = self->_get_bounds;
            if (p == _p8) { d = _d8; }
            else
            {
                d = (get_bounds_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_bounds_delegate));
                if (_p8 == IntPtr.Zero) { _d8 = d; _p8 = p; }
            }
            return d(self);
        }
        
        // GetWorkArea
        private static IntPtr _p9;
        private static get_work_area_delegate _d9;
        
        public static cef_rect_t get_work_area(cef_display_t* self)
        {
            get_work_area_delegate d;
            var p = self->_get_work_area;
            if (p == _p9) { d = _d9; }
            else
            {
                d = (get_work_area_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_work_area_delegate));
                if (_p9 == IntPtr.Zero) { _d9 = d; _p9 = p; }
            }
            return d(self);
        }
        
        // GetRotation
        private static IntPtr _pa;
        private static get_rotation_delegate _da;
        
        public static int get_rotation(cef_display_t* self)
        {
            get_rotation_delegate d;
            var p = self->_get_rotation;
            if (p == _pa) { d = _da; }
            else
            {
                d = (get_rotation_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_rotation_delegate));
                if (_pa == IntPtr.Zero) { _da = d; _pa = p; }
            }
            return d(self);
        }
        
    }
}
