//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_browser_view_delegate_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _get_preferred_size;
        internal IntPtr _get_minimum_size;
        internal IntPtr _get_maximum_size;
        internal IntPtr _get_height_for_width;
        internal IntPtr _on_parent_view_changed;
        internal IntPtr _on_child_view_changed;
        internal IntPtr _on_window_changed;
        internal IntPtr _on_layout_changed;
        internal IntPtr _on_focus;
        internal IntPtr _on_blur;
        internal IntPtr _on_theme_changed;
        internal IntPtr _on_browser_created;
        internal IntPtr _on_browser_destroyed;
        internal IntPtr _get_delegate_for_popup_browser_view;
        internal IntPtr _on_popup_browser_view_created;
        internal IntPtr _get_chrome_toolbar_type;
        internal IntPtr _use_frameless_window_for_picture_in_picture;
        internal IntPtr _on_gesture_command;
        internal IntPtr _get_browser_runtime_style;
        internal IntPtr _allow_move_for_picture_in_picture;
        internal IntPtr _allow_picture_in_picture_without_user_activation;
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void add_ref_delegate(cef_browser_view_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int release_delegate(cef_browser_view_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_one_ref_delegate(cef_browser_view_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_at_least_one_ref_delegate(cef_browser_view_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_preferred_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_minimum_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_maximum_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int get_height_for_width_delegate(cef_view_delegate_t* self, cef_view_t* view, int width);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_parent_view_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added, cef_view_t* parent);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_child_view_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added, cef_view_t* child);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_layout_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, cef_rect_t* new_bounds);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_focus_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_blur_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_theme_changed_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_browser_created_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view, cef_browser_t* browser);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_browser_destroyed_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view, cef_browser_t* browser);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_browser_view_delegate_t* get_delegate_for_popup_browser_view_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view, cef_browser_settings_t* settings, cef_client_t* client, int is_devtools);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int on_popup_browser_view_created_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view, cef_browser_view_t* popup_browser_view, int is_devtools);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate CefChromeToolbarType get_chrome_toolbar_type_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int use_frameless_window_for_picture_in_picture_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int on_gesture_command_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view, CefGestureCommand gesture_command);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate CefRuntimeStyle get_browser_runtime_style_delegate(cef_browser_view_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int allow_move_for_picture_in_picture_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int allow_picture_in_picture_without_user_activation_delegate(cef_browser_view_delegate_t* self, cef_browser_view_t* browser_view);
        
        private static int _sizeof;
        
        static cef_browser_view_delegate_t()
        {
            _sizeof = Marshal.SizeOf(typeof(cef_browser_view_delegate_t));
        }
        
        internal static cef_browser_view_delegate_t* Alloc()
        {
            var ptr = (cef_browser_view_delegate_t*)Marshal.AllocHGlobal(_sizeof);
            *ptr = new cef_browser_view_delegate_t();
            ptr->_base._size = (UIntPtr)_sizeof;
            return ptr;
        }
        
        internal static void Free(cef_browser_view_delegate_t* ptr)
        {
            Marshal.FreeHGlobal((IntPtr)ptr);
        }
        
    }
}
