//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_panel_delegate_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _get_preferred_size;
        internal IntPtr _get_minimum_size;
        internal IntPtr _get_maximum_size;
        internal IntPtr _get_height_for_width;
        internal IntPtr _on_parent_view_changed;
        internal IntPtr _on_child_view_changed;
        internal IntPtr _on_window_changed;
        internal IntPtr _on_layout_changed;
        internal IntPtr _on_focus;
        internal IntPtr _on_blur;
        internal IntPtr _on_theme_changed;
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void add_ref_delegate(cef_panel_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int release_delegate(cef_panel_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_one_ref_delegate(cef_panel_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int has_at_least_one_ref_delegate(cef_panel_delegate_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_preferred_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_minimum_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate cef_size_t get_maximum_size_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate int get_height_for_width_delegate(cef_view_delegate_t* self, cef_view_t* view, int width);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_parent_view_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added, cef_view_t* parent);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_child_view_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added, cef_view_t* child);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_window_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, int added);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_layout_changed_delegate(cef_view_delegate_t* self, cef_view_t* view, cef_rect_t* new_bounds);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_focus_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_blur_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        internal delegate void on_theme_changed_delegate(cef_view_delegate_t* self, cef_view_t* view);
        
        private static int _sizeof;
        
        static cef_panel_delegate_t()
        {
            _sizeof = Marshal.SizeOf(typeof(cef_panel_delegate_t));
        }
        
        internal static cef_panel_delegate_t* Alloc()
        {
            var ptr = (cef_panel_delegate_t*)Marshal.AllocHGlobal(_sizeof);
            *ptr = new cef_panel_delegate_t();
            ptr->_base._size = (UIntPtr)_sizeof;
            return ptr;
        }
        
        internal static void Free(cef_panel_delegate_t* ptr)
        {
            Marshal.FreeHGlobal((IntPtr)ptr);
        }
        
    }
}
